/**
 * Provenance Interface
 * 
 * Mandatory metadata for all ingested signals.
 * Complies with WIT-ESI-003 (Required fields) and WIT-ESI-004 (Idempotency).
 */

import { AdapterId, AdapterVersion, VendorRef } from "./types";

export interface Provenance {
    adapter_id: AdapterId;
    adapter_version: AdapterVersion;
    source_ref: VendorRef;      // Opaque vendor pointer
    received_at: string;        // ISO timestamp
    /**
     * Canonical Format: `${adapter_id}:${source_ref}:${signal_class}`
     * Enforced by core, generated by adapter.
     */
    idempotency_key: string;    // Required for WIT-ESI-004
    vendor_trace_id?: string;   // Observability only
}
