/**
 * Configuración global reutilizable del Dev-Kit
 */

export const ENV_KEYS = {
    NODE_ENV: 'NODE_ENV',
    VITE_SUPABASE_URL: 'VITE_SUPABASE_URL',
    VITE_SUPABASE_ANON_KEY: 'VITE_SUPABASE_ANON_KEY',
    VITE_OPENAI_API_KEY: 'VITE_OPENAI_API_KEY',
    BASE_URL: 'VITE_BASE_URL'
} as const;

export const ROLES = {
    EMPLOYEE: 'EMPLOYEE',
    MANAGER: 'MANAGER',
    ADMIN: 'ADMIN',
    OWNER: 'OWNER',
    SUPER_ADMIN: 'SUPER_ADMIN'
} as const;

export const PERMISSIONS = {
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    MANAGE_USERS: 'MANAGE_USERS',
    MANAGE_COMPANY: 'MANAGE_COMPANY',
    ACCESS_ADMIN: 'ACCESS_ADMIN',
    ACCESS_SUPER_ADMIN: 'ACCESS_SUPER_ADMIN'
} as const;
