#Requires -Version 5.1
<#
.SYNOPSIS
    Configurador Automatico del Entorno de Desarrollo VThink 1.0
    
.DESCRIPTION
    Script para configurar automaticamente el entorno de desarrollo con todas las optimizaciones.
    Crea aliases, configura variables de entorno, y prepara el workspace.
    
.EXAMPLE
    .\Setup-DevEnvironment-Fixed.ps1
    Configura el entorno de desarrollo completo
    
.NOTES
    Version: 1.0
    Author: VThink Development Team
    Created: 2025-01-01
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Continue"

# Colores
$Colors = @{
    Success = 'Green'
    Info = 'Cyan'
    Warning = 'Yellow'
    Header = 'Magenta'
}

function Write-ColorOutput {
    param([string]$Message, [string]$Color = 'White', [string]$Prefix = "")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $fullMessage = if ($Prefix) { "[$timestamp] $Prefix $Message" } else { "[$timestamp] $Message" }
    Write-Host $fullMessage -ForegroundColor $Color
}

function Write-Header {
    param([string]$Title)
    $border = "=" * 60
    Write-Host ""
    Write-ColorOutput $border -Color $Colors.Header
    Write-ColorOutput " $Title" -Color $Colors.Header
    Write-ColorOutput $border -Color $Colors.Header
    Write-Host ""
}

Write-Header "CONFIGURADOR DEL ENTORNO VTHINK 1.0"

# 1. Crear aliases utiles
Write-ColorOutput "Creando aliases de desarrollo..." -Color $Colors.Info -Prefix "ALIAS"

$profilePath = $PROFILE
if (-not (Test-Path $profilePath)) {
    New-Item -Path $profilePath -ItemType File -Force | Out-Null
}

$projectRoot = "C:\IA Marcelo Labs\vibethink-orchestrator-main"
$dashboardPath = "$projectRoot\apps\dashboard"

$aliases = @"

# VThink Development Aliases - Auto Generated
# Navegacion rapida
function Set-VThinkRoot { Set-Location '$projectRoot' }
function Set-VThinkDash { Set-Location '$dashboardPath' }

Set-Alias -Name vthink -Value Set-VThinkRoot
Set-Alias -Name vdash -Value Set-VThinkDash

# Comandos de desarrollo
function Start-VThinkDev { 
    Set-Location '$projectRoot\dev-tools\scripts'
    & '.\Optimize-DevServer.ps1' -Mode Quick 
}

function Start-VThinkDeep { 
    Set-Location '$projectRoot\dev-tools\scripts'
    & '.\Optimize-DevServer.ps1' -Mode Deep 
}

function Show-VThinkStatus { 
    Set-Location '$projectRoot\dev-tools\scripts'
    & '.\Optimize-DevServer.ps1' -Mode Monitor 
}

function Reset-VThinkDev { 
    Set-Location '$projectRoot\dev-tools\scripts'
    & '.\Optimize-DevServer.ps1' -Mode Reset 
}

Set-Alias -Name vdev -Value Start-VThinkDev
Set-Alias -Name vdeep -Value Start-VThinkDeep  
Set-Alias -Name vstatus -Value Show-VThinkStatus
Set-Alias -Name vreset -Value Reset-VThinkDev

# Funcion para mostrar ayuda de VThink
function Show-VThinkHelp {
    Write-Host ""
    Write-Host "VThink Development Commands:" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "  Navigation:" -ForegroundColor Cyan
    Write-Host "    vthink        # Go to project root" -ForegroundColor White
    Write-Host "    vdash         # Go to dashboard app" -ForegroundColor White
    Write-Host ""
    Write-Host "  Development:" -ForegroundColor Cyan  
    Write-Host "    vdev          # Start optimized dev server (Quick)" -ForegroundColor White
    Write-Host "    vdeep         # Start with deep optimization" -ForegroundColor White
    Write-Host "    vstatus       # Show performance status" -ForegroundColor White
    Write-Host "    vreset        # Complete project reset" -ForegroundColor White
    Write-Host ""
    Write-Host "  Help:" -ForegroundColor Cyan
    Write-Host "    vhelp         # Show this help" -ForegroundColor White
    Write-Host ""
}

Set-Alias -Name vhelp -Value Show-VThinkHelp

Write-Host "VThink aliases loaded! Type 'vhelp' for commands." -ForegroundColor Green

"@

Add-Content -Path $profilePath -Value $aliases
Write-ColorOutput "Aliases creados en el perfil de PowerShell" -Color $Colors.Success

# 2. Configurar variables de entorno permanentes
Write-ColorOutput "Configurando variables de entorno..." -Color $Colors.Info -Prefix "ENV"

$envVars = @{
    'VTHINK_ROOT' = $projectRoot
    'VTHINK_DASHBOARD' = $dashboardPath
    'NODE_OPTIONS' = '--max-old-space-size=4096'
    'NEXT_TELEMETRY_DISABLED' = '1'
}

foreach ($var in $envVars.Keys) {
    [Environment]::SetEnvironmentVariable($var, $envVars[$var], 'User')
    Write-ColorOutput "$var = $($envVars[$var])" -Color $Colors.Success
}

# 3. Crear archivos de configuracion
Write-ColorOutput "Creando archivos de configuracion..." -Color $Colors.Info -Prefix "CONFIG"

# .env.local para desarrollo
$envLocalContent = @"
# VThink Development Environment
# Auto-generated by Setup-DevEnvironment.ps1

NODE_OPTIONS=--max-old-space-size=4096
NEXT_TELEMETRY_DISABLED=1
WATCHPACK_POLLING=1000
NODE_ENV=development

# Next.js optimizations
NEXT_PRIVATE_LOCAL_WEBPACK=1
NEXT_PRIVATE_DEBUG_CACHE=0

# Development flags
VTHINK_DEV_MODE=true
VTHINK_OPTIMIZED=true
"@

$envLocalPath = Join-Path $dashboardPath ".env.local"

Set-Content -Path $envLocalPath -Value $envLocalContent -Encoding UTF8
Write-ColorOutput ".env.local creado en dashboard" -Color $Colors.Success

# 4. Crear script de inicio rapido en desktop
Write-ColorOutput "Creando acceso directo en el escritorio..." -Color $Colors.Info -Prefix "DESKTOP"

$desktopPath = [Environment]::GetFolderPath("Desktop")
$shortcutPath = Join-Path $desktopPath "VThink-Dev-Server.bat"

$shortcutContent = @"
@echo off
title VThink Development Server
cd /d "$projectRoot\dev-tools\scripts"
powershell.exe -ExecutionPolicy Bypass -File ".\Optimize-DevServer.ps1" -Mode Quick
pause
"@

Set-Content -Path $shortcutPath -Value $shortcutContent -Encoding ASCII
Write-ColorOutput "Acceso directo creado en el escritorio" -Color $Colors.Success

# 5. Verificar instalaciones necesarias
Write-ColorOutput "Verificando herramientas requeridas..." -Color $Colors.Info -Prefix "CHECK"

$tools = @{
    'node' = 'Node.js'
    'npm' = 'NPM'
    'git' = 'Git'
}

foreach ($tool in $tools.Keys) {
    try {
        $version = & $tool --version 2>$null
        Write-ColorOutput "$($tools[$tool]): $version" -Color $Colors.Success
    }
    catch {
        Write-ColorOutput "$($tools[$tool]): No instalado" -Color $Colors.Warning
    }
}

# Resumen final
Write-Header "CONFIGURACION COMPLETADA"

Write-ColorOutput "Resumen de configuracion:" -Color $Colors.Header
Write-ColorOutput "   Aliases de PowerShell creados" -Color $Colors.Success
Write-ColorOutput "   Variables de entorno configuradas" -Color $Colors.Success  
Write-ColorOutput "   Archivo .env.local creado" -Color $Colors.Success
Write-ColorOutput "   Acceso directo en escritorio" -Color $Colors.Success

Write-Host ""
Write-ColorOutput "Listo para desarrollar!" -Color $Colors.Success -Prefix "READY"
Write-ColorOutput "   • Reinicia PowerShell para usar los aliases" -Color $Colors.Info
Write-ColorOutput "   • Ejecuta 'vhelp' para ver todos los comandos" -Color $Colors.Info
Write-ColorOutput "   • Ejecuta 'vdev' para iniciar el servidor optimizado" -Color $Colors.Info

Write-Host ""