name: Canon Protection Gate

# =============================================================================
# VIBETHINK ORCHESTRATOR - CANON PROTECTION WORKFLOW
# =============================================================================
# This workflow enforces strict governance over Canon and FIT documents.
# Any changes to these files require Principal Architect approval via CODEOWNERS.
# =============================================================================

on:
  pull_request:
    paths:
      - 'docs/canon/**'
      - 'docs/fits/**'
      - 'docs/registry/**'
      - '.github/CODEOWNERS'
      - 'AGENTS.md'
      - 'AI_STABILITY_RULES.md'

jobs:
  canon-protection:
    name: Canon & Governance Protection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Identify Changed Canon Files
        id: changed-files
        run: |
          echo "ðŸ” Checking for Canon/Governance file changes..."

          CANON_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E "^docs/canon/|^docs/fits/|^docs/registry/" || true)
          GOVERNANCE_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E "^\.github/CODEOWNERS$|^AGENTS\.md$|^AI_STABILITY_RULES\.md$" || true)

          if [ -n "$CANON_FILES" ]; then
            echo "ðŸ“œ Canon files changed:"
            echo "$CANON_FILES"
            echo "canon_changed=true" >> $GITHUB_OUTPUT
          else
            echo "canon_changed=false" >> $GITHUB_OUTPUT
          fi

          if [ -n "$GOVERNANCE_FILES" ]; then
            echo "ðŸ›ï¸ Governance files changed:"
            echo "$GOVERNANCE_FILES"
            echo "governance_changed=true" >> $GITHUB_OUTPUT
          else
            echo "governance_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate FIT Claims
        if: steps.changed-files.outputs.canon_changed == 'true'
        run: |
          echo "ðŸ” Validating FIT claims in documentation..."
          node scripts/validate-fit-claims.mjs

      - name: Validate Methodology Registry
        if: steps.changed-files.outputs.canon_changed == 'true'
        run: |
          echo "ðŸ” Validating methodology governance..."
          npm run validate:methodology-adoption

      - name: Canon Change Warning
        if: steps.changed-files.outputs.canon_changed == 'true' || steps.changed-files.outputs.governance_changed == 'true'
        run: |
          echo ""
          echo "âš ï¸ =============================================="
          echo "âš ï¸  CANON / GOVERNANCE FILES MODIFIED"
          echo "âš ï¸ =============================================="
          echo ""
          echo "This PR modifies protected architectural documents."
          echo ""
          echo "Requirements for merge:"
          echo "  1. Principal Architect must approve (via CODEOWNERS)"
          echo "  2. All CI gates must pass"
          echo "  3. FIT claims must be valid (no prohibited claims)"
          echo ""
          echo "If this change redefines architecture or domain:"
          echo "  - Ensure it aligns with Canon principles"
          echo "  - Update FIT gates if necessary"
          echo "  - Document the decision rationale"
          echo ""
          echo "ðŸ“– See: docs/canon/00_CANON_INDEX.md"
          echo "ðŸ“– See: docs/canon/METHODOLOGY_EVALUATION_FRAMEWORK.md"
          echo ""

      - name: Post PR Comment
        if: steps.changed-files.outputs.canon_changed == 'true' || steps.changed-files.outputs.governance_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            const body = `## ðŸ›ï¸ Canon/Governance Change Detected

This PR modifies protected architectural documents.

### Requirements for Merge:
- [ ] Principal Architect approval (enforced by CODEOWNERS)
- [ ] All CI gates pass
- [ ] FIT claims are valid
- [ ] Changes align with Canon principles

### Files Changed:
\`\`\`
${process.env.CANON_FILES || 'See workflow output'}
\`\`\`

> ðŸ“– Reference: [Canon Index](docs/canon/00_CANON_INDEX.md) | [Methodology Framework](docs/canon/METHODOLOGY_EVALUATION_FRAMEWORK.md)

---
*This comment was automatically generated by the Canon Protection workflow.*`;

            // Check if we already commented
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number,
            });

            const botComment = comments.data.find(c =>
              c.user.type === 'Bot' && c.body.includes('Canon/Governance Change Detected')
            );

            if (!botComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body,
              });
            }
