#!/usr/bin/env tsx

/**
 * Mock Generator Script
 * 
 * Genera mocks automáticamente basado en:
 * - Tipos de TypeScript
 * - APIs de Supabase
 * - Servicios externos
 * 
 * @author AI Pair Platform - Testing Team
 * @version 1.0.0
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

interface MockConfig {
  name: string;
  type: 'api' | 'service' | 'component';
  template: () => string;
  outputPath: string;
}

// Configuración de mocks
const mockConfigs: MockConfig[] = [
  {
    name: 'supabase-auth',
    type: 'api',
    template: generateSupabaseAuthMock,
    outputPath: 'tests/mocks/handlers/supabase-auth.ts',
  },
  {
    name: 'supabase-companies',
    type: 'api',
    template: generateSupabaseCompaniesMock,
    outputPath: 'tests/mocks/handlers/supabase-companies.ts',
  },
  {
    name: 'supabase-users',
    type: 'api',
    template: generateSupabaseUsersMock,
    outputPath: 'tests/mocks/handlers/supabase-users.ts',
  },
  {
    name: 'openai-api',
    type: 'api',
    template: generateOpenAIMock,
    outputPath: 'tests/mocks/handlers/openai-api.ts',
  },
  {
    name: 'google-workspace',
    type: 'api',
    template: generateGoogleWorkspaceMock,
    outputPath: 'tests/mocks/handlers/google-workspace.ts',
  },
  {
    name: 'user-factories',
    type: 'service',
    template: generateUserFactories,
    outputPath: 'tests/mocks/factories/user-factories.ts',
  },
  {
    name: 'company-factories',
    type: 'service',
    template: generateCompanyFactories,
    outputPath: 'tests/mocks/factories/company-factories.ts',
  },
  {
    name: 'configuration-factories',
    type: 'service',
    template: generateConfigurationFactories,
    outputPath: 'tests/mocks/factories/configuration-factories.ts',
  },
];

async function main() {
  console.log('🔧 Generating mocks...');

  // Crear directorios si no existen
  const directories = [
    'tests/mocks/handlers',
    'tests/mocks/factories',
    'tests/mocks/data',
  ];

  directories.forEach(dir => {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      console.log(`📁 Created directory: ${dir}`);
    }
  });

  // Generar mocks
  for (const config of mockConfigs) {
    try {
      const content = config.template();
      writeFileSync(config.outputPath, content, 'utf8');
      console.log(`✅ Generated: ${config.outputPath}`);
    } catch (error) {
      console.error(`❌ Error generating ${config.name}:`, error);
    }
  }

  // Generar archivo de índice
  generateIndexFile();

  console.log('🎉 Mock generation completed!');
}

function generateSupabaseAuthMock(): string {
  return `/**
 * Supabase Auth Mock Handlers
 * 
 * Mock handlers for Supabase authentication endpoints
 * 
 * @generated by mock-generator
 */

import { http, HttpResponse } from 'msw';
import { createMockUser } from '../factories/user-factories';

export const supabaseAuthHandlers = [
  // Login endpoint
  http.post('https://test.supabase.co/auth/v1/token', () => {
    return HttpResponse.json({
      access_token: 'test-access-token',
      refresh_token: 'test-refresh-token',
      expires_in: 3600,
      token_type: 'bearer',
      user: createMockUser(),
    });
  }),

  // Get user session
  http.get('https://test.supabase.co/auth/v1/user', () => {
    return HttpResponse.json(createMockUser());
  }),

  // Refresh token
  http.post('https://test.supabase.co/auth/v1/token', ({ request }) => {
    const url = new URL(request.url);
    const grantType = url.searchParams.get('grant_type');
    
    if (grantType === 'refresh_token') {
      return HttpResponse.json({
        access_token: 'new-access-token',
        refresh_token: 'new-refresh-token',
        expires_in: 3600,
        token_type: 'bearer',
      });
    }
    
    // Default login response
    return HttpResponse.json({
      access_token: 'test-access-token',
      refresh_token: 'test-refresh-token',
      expires_in: 3600,
      token_type: 'bearer',
      user: createMockUser(),
    });
  }),

  // Logout endpoint
  http.post('https://test.supabase.co/auth/v1/logout', () => {
    return HttpResponse.json({ message: 'Logged out successfully' });
  }),

  // Failed login
  http.post('https://test.supabase.co/auth/v1/token', ({ request }) => {
    const url = new URL(request.url);
    const email = url.searchParams.get('email');
    
    if (email === 'wrong@example.com') {
      return HttpResponse.json(
        { error: 'Invalid credentials' },
        { status: 401 }
      );
    }
    
    // Default successful response
    return HttpResponse.json({
      access_token: 'test-access-token',
      refresh_token: 'test-refresh-token',
      expires_in: 3600,
      token_type: 'bearer',
      user: createMockUser(),
    });
  }),
];
`;
}

function generateSupabaseCompaniesMock(): string {
  return `/**
 * Supabase Companies Mock Handlers
 * 
 * Mock handlers for Supabase companies endpoints
 * 
 * @generated by mock-generator
 */

import { http, HttpResponse } from 'msw';
import { createMockCompany } from '../factories/company-factories';

export const supabaseCompaniesHandlers = [
  // Get all companies
  http.get('https://test.supabase.co/rest/v1/companies', () => {
    return HttpResponse.json([
      createMockCompany(),
      createMockCompany({ id: 'test-company-2', name: 'Test Company 2' }),
      createMockCompany({ id: 'test-company-3', name: 'Test Company 3' }),
    ]);
  }),

  // Get company by ID
  http.get('https://test.supabase.co/rest/v1/companies/:id', ({ params }) => {
    return HttpResponse.json(createMockCompany({ id: params.id }));
  }),

  // Create company
  http.post('https://test.supabase.co/rest/v1/companies', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json(createMockCompany(body));
  }),

  // Update company
  http.patch('https://test.supabase.co/rest/v1/companies/:id', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json(createMockCompany(body));
  }),

  // Delete company
  http.delete('https://test.supabase.co/rest/v1/companies/:id', () => {
    return HttpResponse.json({ message: 'Company deleted successfully' });
  }),

  // Get company limits
  http.post('https://test.supabase.co/rest/v1/rpc/get_company_limits', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json({
      max_users: 25,
      max_monthly_ai_requests: 10000,
      max_monthly_scraping_pages: 1000,
      max_storage_gb: 10,
      features: ['ai_generation', 'document_processing'],
      current_usage: {
        users: 15,
        ai_requests: 5000,
        scraping_pages: 500,
        storage_mb: 5000,
      },
    });
  }),
];
`;
}

function generateSupabaseUsersMock(): string {
  return `/**
 * Supabase Users Mock Handlers
 * 
 * Mock handlers for Supabase user profiles endpoints
 * 
 * @generated by mock-generator
 */

import { http, HttpResponse } from 'msw';
import { createMockUser } from '../factories/user-factories';

export const supabaseUsersHandlers = [
  // Get all users
  http.get('https://test.supabase.co/rest/v1/user_profiles', ({ request }) => {
    const url = new URL(request.url);
    const companyId = url.searchParams.get('company_id');
    
    if (companyId) {
      // Return users filtered by company
      return HttpResponse.json([
        createMockUser({ company_id: companyId }),
        createMockUser({ 
          id: 'test-user-2', 
          email: 'user2@company.com',
          company_id: companyId 
        }),
      ]);
    }
    
    // Return all users
    return HttpResponse.json([
      createMockUser(),
      createMockUser({ id: 'test-user-2', email: 'user2@company.com' }),
      createMockUser({ id: 'test-user-3', email: 'user3@company.com' }),
    ]);
  }),

  // Get user by ID
  http.get('https://test.supabase.co/rest/v1/user_profiles/:id', ({ params }) => {
    return HttpResponse.json(createMockUser({ id: params.id }));
  }),

  // Create user
  http.post('https://test.supabase.co/rest/v1/user_profiles', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json(createMockUser(body));
  }),

  // Update user
  http.patch('https://test.supabase.co/rest/v1/user_profiles/:id', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json(createMockUser(body));
  }),

  // Delete user
  http.delete('https://test.supabase.co/rest/v1/user_profiles/:id', () => {
    return HttpResponse.json({ message: 'User deleted successfully' });
  }),

  // Get user permissions
  http.post('https://test.supabase.co/rest/v1/rpc/get_user_permissions', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json({
      user_id: body.user_id,
      permissions: ['read', 'write', 'admin'],
      role: 'ADMIN',
      company_id: body.company_id,
    });
  }),
];
`;
}

function generateOpenAIMock(): string {
  return `/**
 * OpenAI API Mock Handlers
 * 
 * Mock handlers for OpenAI API endpoints
 * 
 * @generated by mock-generator
 */

import { http, HttpResponse } from 'msw';

export const openAIHandlers = [
  // Chat completions
  http.post('https://api.openai.com/v1/chat/completions', async ({ request }) => {
    const body = await request.json();
    
    // Generate different responses based on input
    let responseContent = 'This is a default AI response.';
    
    if (body.messages?.some((msg: any) => msg.content.includes('summarize'))) {
      responseContent = 'This is a summary of the provided content.';
    } else if (body.messages?.some((msg: any) => msg.content.includes('translate'))) {
      responseContent = 'This is the translated content.';
    } else if (body.messages?.some((msg: any) => msg.content.includes('analyze'))) {
      responseContent = 'This is the analysis of the provided data.';
    }
    
    return HttpResponse.json({
      id: 'test-completion-id',
      object: 'chat.completion',
      created: Math.floor(Date.now() / 1000),
      model: body.model || 'gpt-4',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: responseContent,
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: body.messages?.length * 10 || 10,
        completion_tokens: responseContent.split(' ').length,
        total_tokens: (body.messages?.length * 10 || 10) + responseContent.split(' ').length,
      },
    });
  }),

  // Embeddings
  http.post('https://api.openai.com/v1/embeddings', async ({ request }) => {
    const body = await request.json();
    
    return HttpResponse.json({
      object: 'list',
      data: [
        {
          object: 'embedding',
          embedding: Array(1536).fill(0.1), // Mock embedding vector
          index: 0,
        },
      ],
      model: body.model || 'text-embedding-ada-002',
      usage: {
        prompt_tokens: body.input?.length || 10,
        total_tokens: body.input?.length || 10,
      },
    });
  }),

  // Rate limiting
  http.post('https://api.openai.com/v1/chat/completions', ({ request }) => {
    const url = new URL(request.url);
    const apiKey = request.headers.get('authorization');
    
    if (apiKey === 'Bearer invalid-key') {
      return HttpResponse.json(
        { error: { message: 'Rate limit exceeded' } },
        { status: 429 }
      );
    }
    
    // Default successful response
    return HttpResponse.json({
      id: 'test-completion-id',
      choices: [{ message: { content: 'Test response' } }],
    });
  }),

  // Invalid API key
  http.post('https://api.openai.com/v1/chat/completions', ({ request }) => {
    const apiKey = request.headers.get('authorization');
    
    if (apiKey === 'Bearer invalid-key') {
      return HttpResponse.json(
        { error: { message: 'Invalid API key' } },
        { status: 401 }
      );
    }
    
    // Default successful response
    return HttpResponse.json({
      id: 'test-completion-id',
      choices: [{ message: { content: 'Test response' } }],
    });
  }),
];
`;
}

function generateGoogleWorkspaceMock(): string {
  return `/**
 * Google Workspace API Mock Handlers
 * 
 * Mock handlers for Google Workspace API endpoints
 * 
 * @generated by mock-generator
 */

import { http, HttpResponse } from 'msw';

export const googleWorkspaceHandlers = [
  // OAuth token
  http.post('https://www.googleapis.com/oauth2/v4/token', () => {
    return HttpResponse.json({
      access_token: 'test-google-access-token',
      refresh_token: 'test-google-refresh-token',
      expires_in: 3600,
      token_type: 'Bearer',
    });
  }),

  // User info
  http.get('https://www.googleapis.com/oauth2/v2/userinfo', () => {
    return HttpResponse.json({
      id: 'test-google-user-id',
      email: 'test@example.com',
      name: 'Test User',
      picture: 'https://example.com/avatar.jpg',
      verified_email: true,
    });
  }),

  // Google Docs - Create document
  http.post('https://docs.googleapis.com/v1/documents', async ({ request }) => {
    const body = await request.json();
    
    return HttpResponse.json({
      documentId: 'test-document-id',
      title: body.title || 'Test Document',
      body: {
        content: [
          {
            paragraph: {
              elements: [
                {
                  textRun: {
                    content: 'Test content',
                  },
                },
              ],
            },
          },
        ],
      },
    });
  }),

  // Google Drive - Upload file
  http.post('https://drive.googleapis.com/drive/v3/files', async ({ request }) => {
    const body = await request.json();
    
    return HttpResponse.json({
      id: 'test-file-id',
      name: body.name || 'Test File',
      mimeType: body.mimeType || 'application/vnd.google-apps.document',
      webViewLink: 'https://docs.google.com/document/d/test-file-id/edit',
      size: '1024',
      createdTime: new Date().toISOString(),
      modifiedTime: new Date().toISOString(),
    });
  }),

  // Google Drive - List files
  http.get('https://drive.googleapis.com/drive/v3/files', () => {
    return HttpResponse.json({
      files: [
        {
          id: 'file-1',
          name: 'Document 1',
          mimeType: 'application/vnd.google-apps.document',
          webViewLink: 'https://docs.google.com/document/d/file-1/edit',
        },
        {
          id: 'file-2',
          name: 'Document 2',
          mimeType: 'application/vnd.google-apps.document',
          webViewLink: 'https://docs.google.com/document/d/file-2/edit',
        },
      ],
      nextPageToken: null,
    });
  }),
];
`;
}

function generateUserFactories(): string {
  return `/**
 * User Factories
 * 
 * Factory functions for creating mock user data
 * 
 * @generated by mock-generator
 */

export interface MockUser {
  id: string;
  email: string;
  full_name: string;
  role: 'EMPLOYEE' | 'MANAGER' | 'ADMIN' | 'OWNER' | 'SUPER_ADMIN';
  company_id: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const createMockUser = (overrides: Partial<MockUser> = {}): MockUser => ({
  id: 'test-user-id',
  email: 'test@example.com',
  full_name: 'Test User',
  role: 'ADMIN',
  company_id: 'test-company-id',
  is_active: true,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  ...overrides,
});

export const createMockUserWithRole = (role: MockUser['role']) => 
  createMockUser({ role });

export const createMockUserForCompany = (companyId: string) => 
  createMockUser({ company_id: companyId });

export const createMockSuperAdmin = () => 
  createMockUser({
    email: 'admin@VibeThink.co',
    role: 'SUPER_ADMIN',
    company_id: 'VibeThink-platform',
  });

export const createMockCompanyOwner = (companyId: string) => 
  createMockUser({
    role: 'OWNER',
    company_id: companyId,
  });

export const createMockEmployee = (companyId: string) => 
  createMockUser({
    role: 'EMPLOYEE',
    company_id: companyId,
  });

export const createMockManager = (companyId: string) => 
  createMockUser({
    role: 'MANAGER',
    company_id: companyId,
  });

export const createMockAdmin = (companyId: string) => 
  createMockUser({
    role: 'ADMIN',
    company_id: companyId,
  });

// Test data arrays
export const mockUsers = [
  createMockUser(),
  createMockUser({ id: 'user-2', email: 'user2@example.com' }),
  createMockUser({ id: 'user-3', email: 'user3@example.com' }),
];

export const mockUsersByRole = {
  EMPLOYEE: createMockEmployee('test-company-id'),
  MANAGER: createMockManager('test-company-id'),
  ADMIN: createMockAdmin('test-company-id'),
  OWNER: createMockCompanyOwner('test-company-id'),
  SUPER_ADMIN: createMockSuperAdmin(),
};
`;
}

function generateCompanyFactories(): string {
  return `/**
 * Company Factories
 * 
 * Factory functions for creating mock company data
 * 
 * @generated by mock-generator
 */

export interface MockCompany {
  id: string;
  name: string;
  slug: string;
  status: 'ACTIVE' | 'TRIAL' | 'SUSPENDED' | 'CANCELLED';
  subscription_plan: 'STARTER' | 'PROFESSIONAL' | 'ENTERPRISE';
  max_users: number;
  max_monthly_ai_requests: number;
  max_monthly_scraping_pages: number;
  max_storage_gb: number;
  created_at: string;
  updated_at: string;
}

export const createMockCompany = (overrides: Partial<MockCompany> = {}): MockCompany => ({
  id: 'test-company-id',
  name: 'Test Company',
  slug: 'test-company',
  status: 'ACTIVE',
  subscription_plan: 'PROFESSIONAL',
  max_users: 25,
  max_monthly_ai_requests: 10000,
  max_monthly_scraping_pages: 1000,
  max_storage_gb: 10,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  ...overrides,
});

export const createMockStarterCompany = () => 
  createMockCompany({
    subscription_plan: 'STARTER',
    max_users: 5,
    max_monthly_ai_requests: 1000,
    max_monthly_scraping_pages: 100,
    max_storage_gb: 1,
  });

export const createMockProfessionalCompany = () => 
  createMockCompany({
    subscription_plan: 'PROFESSIONAL',
    max_users: 25,
    max_monthly_ai_requests: 10000,
    max_monthly_scraping_pages: 1000,
    max_storage_gb: 10,
  });

export const createMockEnterpriseCompany = () => 
  createMockCompany({
    subscription_plan: 'ENTERPRISE',
    max_users: 100,
    max_monthly_ai_requests: 100000,
    max_monthly_scraping_pages: 10000,
    max_storage_gb: 100,
  });

export const createMockTrialCompany = () => 
  createMockCompany({
    status: 'TRIAL',
    subscription_plan: 'STARTER',
  });

export const createMockSuspendedCompany = () => 
  createMockCompany({
    status: 'SUSPENDED',
  });

export const createMockCancelledCompany = () => 
  createMockCompany({
    status: 'CANCELLED',
  });

// Test data arrays
export const mockCompanies = [
  createMockCompany(),
  createMockCompany({ id: 'company-2', name: 'Test Company 2' }),
  createMockCompany({ id: 'company-3', name: 'Test Company 3' }),
];

export const mockCompaniesByPlan = {
  STARTER: createMockStarterCompany(),
  PROFESSIONAL: createMockProfessionalCompany(),
  ENTERPRISE: createMockEnterpriseCompany(),
};

export const mockCompaniesByStatus = {
  ACTIVE: createMockCompany(),
  TRIAL: createMockTrialCompany(),
  SUSPENDED: createMockSuspendedCompany(),
  CANCELLED: createMockCancelledCompany(),
};
`;
}

function generateConfigurationFactories(): string {
  return `/**
 * Configuration Factories
 * 
 * Factory functions for creating mock configuration data
 * 
 * @generated by mock-generator
 */

export interface MockConfiguration {
  id: string;
  category: string;
  config_key: string;
  config_value: any;
  description: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const createMockConfiguration = (overrides: Partial<MockConfiguration> = {}): MockConfiguration => ({
  id: 'test-config-id',
  category: 'ai_models',
  config_key: 'openai_models',
  config_value: { models: ['gpt-4', 'gpt-3.5-turbo'] },
  description: 'Test configuration',
  is_active: true,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  ...overrides,
});

export const createMockAIConfiguration = () => 
  createMockConfiguration({
    category: 'ai_models',
    config_key: 'openai_models',
    config_value: {
      models: ['gpt-4', 'gpt-3.5-turbo'],
      default_model: 'gpt-4',
      max_tokens: 4000,
    },
    description: 'OpenAI model configuration',
  });

export const createMockIntegrationConfiguration = () => 
  createMockConfiguration({
    category: 'integrations',
    config_key: 'google_workspace',
    config_value: {
      enabled: true,
      scopes: ['drive', 'docs'],
      redirect_uri: 'https://app.example.com/auth/google/callback',
    },
    description: 'Google Workspace integration settings',
  });

export const createMockSecurityConfiguration = () => 
  createMockConfiguration({
    category: 'security',
    config_key: 'password_policy',
    config_value: {
      min_length: 8,
      require_uppercase: true,
      require_lowercase: true,
      require_numbers: true,
      require_special_chars: true,
    },
    description: 'Password policy configuration',
  });

export const createMockBillingConfiguration = () => 
  createMockConfiguration({
    category: 'billing',
    config_key: 'subscription_plans',
    config_value: {
      starter: {
        price: 29,
        features: ['basic_ai', 'document_processing'],
      },
      professional: {
        price: 99,
        features: ['advanced_ai', 'priority_support'],
      },
      enterprise: {
        price: 299,
        features: ['custom_ai', 'dedicated_support'],
      },
    },
    description: 'Subscription plan configuration',
  });

// Test data arrays
export const mockConfigurations = [
  createMockAIConfiguration(),
  createMockIntegrationConfiguration(),
  createMockSecurityConfiguration(),
  createMockBillingConfiguration(),
];

export const mockConfigurationsByCategory = {
  ai_models: createMockAIConfiguration(),
  integrations: createMockIntegrationConfiguration(),
  security: createMockSecurityConfiguration(),
  billing: createMockBillingConfiguration(),
};
`;
}

function generateIndexFile(): void {
  const indexContent = `/**
 * Mock Index
 * 
 * Centralized exports for all mock handlers and factories
 * 
 * @generated by mock-generator
 */

// Handlers
export { supabaseAuthHandlers } from './handlers/supabase-auth';
export { supabaseCompaniesHandlers } from './handlers/supabase-companies';
export { supabaseUsersHandlers } from './handlers/supabase-users';
export { openAIHandlers } from './handlers/openai-api';
export { googleWorkspaceHandlers } from './handlers/google-workspace';

// Factories
export * from './factories/user-factories';
export * from './factories/company-factories';
export * from './factories/configuration-factories';

// Combine all handlers
import { supabaseAuthHandlers } from './handlers/supabase-auth';
import { supabaseCompaniesHandlers } from './handlers/supabase-companies';
import { supabaseUsersHandlers } from './handlers/supabase-users';
import { openAIHandlers } from './handlers/openai-api';
import { googleWorkspaceHandlers } from './handlers/google-workspace';

export const handlers = [
  ...supabaseAuthHandlers,
  ...supabaseCompaniesHandlers,
  ...supabaseUsersHandlers,
  ...openAIHandlers,
  ...googleWorkspaceHandlers,
];
`;

  writeFileSync('tests/mocks/index.ts', indexContent, 'utf8');
  console.log('✅ Generated: tests/mocks/index.ts');
}

// Ejecutar el script
main().catch(console.error); 