#!/usr/bin/env python3
"""Script para ejecutar tests"""
import subprocess
import sys

def run_tests():
    subprocess.run([sys.executable, "-m", "pytest", "tests", "-v"])

if __name__ == "__main__":
    run_tests()
